services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api
    volumes:
      - ./:/var/www
    working_dir: /var/www
    depends_on:
      - mysql

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

  mysql:
    image: mysql:8.0
    container_name: database
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: laravel
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - ./docker/dbdata:/var/lib/mysql

volumes:
  dbdata:
